# -*- coding: utf-8 -*-
"""ADD1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6ocmA_Q3C2ga3Du9vNepYr3ObjJNlZJ
"""

import os

print(os.listdir("/content"))

import pandas as pd

df = pd.read_csv("//content/TNF_QSAR_preprocessed.csv")

print("Dataset shape:", df.shape)
df.head()

print("Number of compounds:", len(df))
print("Duplicate rows:", df.duplicated().sum())
print("Unique ChEMBL IDs:", df["molecule_chembl_id"].nunique())
print("Unique SMILES:", df["canonical_smiles"].nunique())

print("\nMissing values:")
print(df.isnull().sum())

print("Activity type:")
print(df["standard_type"].value_counts())

print("\nActivity relation:")
print(df["standard_relation"].value_counts())

print("\nActivity units:")
print(df["standard_units"].value_counts())

print("pIC50 statistics:")
print(df["pIC50"].describe())

!pip install rdkit

from rdkit import Chem

print("RDKit imported successfully!")

valid_molecules = []
invalid_smiles = []

for i, smiles in enumerate(df["canonical_smiles"]):
    mol = Chem.MolFromSmiles(smiles)

    if mol is not None:
        valid_molecules.append(mol)
    else:
        invalid_smiles.append((i, smiles))

print("Total SMILES:", len(df))
print("Valid SMILES:", len(valid_molecules))
print("Invalid SMILES:", len(invalid_smiles))

df["Mol"] = df["canonical_smiles"].apply(Chem.MolFromSmiles)

print("Molecules generated:", df["Mol"].notna().sum())

from rdkit.Chem import Descriptors

descriptor_functions = {
    "MolWt": Descriptors.MolWt,
    "LogP": Descriptors.MolLogP,
    "TPSA": Descriptors.TPSA,
    "HBD": Descriptors.NumHDonors,
    "HBA": Descriptors.NumHAcceptors,
    "RotatableBonds": Descriptors.NumRotatableBonds,
    "RingCount": Descriptors.RingCount,
    "HeavyAtomCount": Descriptors.HeavyAtomCount,
}

for name, func in descriptor_functions.items():
    df[name] = df["Mol"].apply(func)

df[list(descriptor_functions.keys())].head()

df[list(descriptor_functions.keys())].describe()

from rdkit.Chem import rdFingerprintGenerator

morgan_gen = rdFingerprintGenerator.GetMorganGenerator(
    radius=2,
    fpSize=2048
)

df["MorganFP"] = df["Mol"].apply(
    lambda mol: morgan_gen.GetFingerprint(mol)
)

print("Morgan fingerprints generated:", df["MorganFP"].notna().sum())
print("Fingerprint length:", len(df["MorganFP"].iloc[0]))

# Molecular descriptors to use as features
descriptor_cols = [
    "MolWt",
    "LogP",
    "TPSA",
    "HBD",
    "HBA",
    "RotatableBonds",
    "RingCount",
    "HeavyAtomCount"
]

# Create X (input features) and y (target)
X_desc = df[descriptor_cols]
y = df["pIC50"]

print("X shape:", X_desc.shape)
print("y shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_desc,
    y,
    test_size=0.20,
    random_state=42
)

print("Training set:", X_train.shape, y_train.shape)
print("Test set:", X_test.shape, y_test.shape)

from sklearn.linear_model import LinearRegression

# Create and train the model
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

print("Linear Regression model trained successfully.")

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

# Predict pIC50 for the test set
y_pred_lr = lr_model.predict(X_test)

# Calculate performance metrics
r2_lr = r2_score(y_test, y_pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
mae_lr = mean_absolute_error(y_test, y_pred_lr)

print("Linear Regression Performance")
print("R²   :", round(r2_lr, 4))
print("RMSE :", round(rmse_lr, 4))
print("MAE  :", round(mae_lr, 4))

from sklearn.ensemble import RandomForestRegressor

# Create Random Forest model
rf_model = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

# Train the model
rf_model.fit(X_train, y_train)

print("Random Forest model trained successfully.")

# Predict pIC50 for the test set
y_pred_rf = rf_model.predict(X_test)

# Calculate performance metrics
r2_rf = r2_score(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
mae_rf = mean_absolute_error(y_test, y_pred_rf)

print("Random Forest Performance")
print("R²   :", round(r2_rf, 4))
print("RMSE :", round(rmse_rf, 4))
print("MAE  :", round(mae_rf, 4))

!pip -q install xgboost

from xgboost import XGBRegressor

# Create XGBoost model
xgb_model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42,
    n_jobs=-1
)

# Train the model
xgb_model.fit(X_train, y_train)

print("XGBoost model trained successfully.")

# Predict pIC50 for the test set
y_pred_xgb = xgb_model.predict(X_test)

# Calculate performance metrics
r2_xgb = r2_score(y_test, y_pred_xgb)
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
mae_xgb = mean_absolute_error(y_test, y_pred_xgb)

print("XGBoost Performance")
print("R²   :", round(r2_xgb, 4))
print("RMSE :", round(rmse_xgb, 4))
print("MAE  :", round(mae_xgb, 4))

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

# Scale the molecular descriptors
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create SVR model
svr_model = SVR(
    kernel="rbf",
    C=10,
    epsilon=0.1
)

# Train the model
svr_model.fit(X_train_scaled, y_train)

print("SVR model trained successfully.")

# Predict pIC50 for the test set
y_pred_svr = svr_model.predict(X_test_scaled)

# Calculate performance metrics
r2_svr = r2_score(y_test, y_pred_svr)
rmse_svr = np.sqrt(mean_squared_error(y_test, y_pred_svr))
mae_svr = mean_absolute_error(y_test, y_pred_svr)

print("SVR Performance")
print("R²   :", round(r2_svr, 4))
print("RMSE :", round(rmse_svr, 4))
print("MAE  :", round(mae_svr, 4))

from sklearn.linear_model import ElasticNet

# Create Elastic Net model
elastic_model = ElasticNet(
    alpha=0.01,
    l1_ratio=0.5,
    random_state=42
)

# Train the model using the original (unscaled) descriptors
elastic_model.fit(X_train, y_train)

print("Elastic Net model trained successfully.")

# Predict pIC50 for the test set
y_pred_elastic = elastic_model.predict(X_test)

# Calculate performance metrics
r2_elastic = r2_score(y_test, y_pred_elastic)
rmse_elastic = np.sqrt(mean_squared_error(y_test, y_pred_elastic))
mae_elastic = mean_absolute_error(y_test, y_pred_elastic)

print("Elastic Net Performance")
print("R²   :", round(r2_elastic, 4))
print("RMSE :", round(rmse_elastic, 4))
print("MAE  :", round(mae_elastic, 4))

from sklearn.model_selection import KFold, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
import numpy as np

# 5-fold cross-validation
cv = KFold(n_splits=5, shuffle=True, random_state=42)

# Define models
models = {
    "Linear Regression": LinearRegression(),

    "Random Forest": RandomForestRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ),

    "XGBoost": XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        random_state=42,
        n_jobs=-1
    ),

    "SVR": Pipeline([
        ("scaler", StandardScaler()),
        ("svr", SVR(kernel="rbf", C=10, epsilon=0.1))
    ]),

    "Elastic Net": Pipeline([
        ("scaler", StandardScaler()),
        ("elastic", ElasticNet(
            alpha=0.01,
            l1_ratio=0.5,
            random_state=42
        ))
    ])
}

# Scoring metrics
scoring = {
    "R2": "r2",
    "RMSE": "neg_root_mean_squared_error",
    "MAE": "neg_mean_absolute_error"
}

# Perform cross-validation
cv_results = {}

for name, model in models.items():
    scores = cross_validate(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring,
        n_jobs=-1
    )

    cv_results[name] = {
        "R²": scores["test_R2"].mean(),
        "RMSE": -scores["test_RMSE"].mean(),
        "MAE": -scores["test_MAE"].mean()
    }

# Display results
for name, result in cv_results.items():
    print(f"\n{name}")
    print("Mean R²   :", round(result["R²"], 4))
    print("Mean RMSE :", round(result["RMSE"], 4))
    print("Mean MAE  :", round(result["MAE"], 4))

# Check fold-by-fold R² for Random Forest and XGBoost

for name in ["Random Forest", "XGBoost"]:
    model = models[name]

    scores = cross_validate(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring="r2",
        n_jobs=-1
    )

    print(f"\n{name} fold R² values:")
    print(np.round(scores["test_score"], 4))
    print("Mean R²:", round(scores["test_score"].mean(), 4))
    print("Std R² :", round(scores["test_score"].std(), 4))

# Train the selected Random Forest model on the full training set
final_rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

final_rf.fit(X_train, y_train)

# Final prediction on the untouched external test set
y_pred_final = final_rf.predict(X_test)

# Final external test metrics
final_r2 = r2_score(y_test, y_pred_final)
final_rmse = np.sqrt(mean_squared_error(y_test, y_pred_final))
final_mae = mean_absolute_error(y_test, y_pred_final)

print("FINAL RANDOM FOREST — EXTERNAL TEST")
print("R²   :", round(final_r2, 4))
print("RMSE :", round(final_rmse, 4))
print("MAE  :", round(final_mae, 4))

from sklearn.preprocessing import StandardScaler
import numpy as np

# Standardize the 8 molecular descriptors using the training set
ad_scaler = StandardScaler()

X_train_ad = ad_scaler.fit_transform(X_train)
X_test_ad = ad_scaler.transform(X_test)

# Calculate centroid of the training chemical space
train_centroid = X_train_ad.mean(axis=0)

# Euclidean distance of every training compound from the centroid
train_distances = np.linalg.norm(
    X_train_ad - train_centroid,
    axis=1
)

# Define a simple distance-based AD threshold
ad_threshold = np.percentile(train_distances, 95)

print("Training compounds:", len(train_distances))
print("AD threshold (95th percentile):", round(ad_threshold, 4))
print("Maximum training distance:", round(train_distances.max(), 4))

# Calculate distance of each external test compound from training centroid
test_distances = np.linalg.norm(
    X_test_ad - train_centroid,
    axis=1
)

# Determine AD status
test_in_ad = test_distances <= ad_threshold

print("External test compounds:", len(test_distances))
print("Within AD:", test_in_ad.sum())
print("Outside AD:", (~test_in_ad).sum())
print("Percentage within AD:", round(test_in_ad.mean() * 100, 2), "%")

# Define the 8 phytochemicals and their SMILES

phytochemicals = {
    "Quercetin": "C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)O)O",
    "Resveratrol": "C1=CC(=CC=C1/C=C/C2=CC(=CC(=C2)O)O)O",
    "Berberine": "COC1=C(C2=C[N+]3=C(C=C2C=C1)C4=CC5=C(C=C4CC3)OCO5)OC",
    "Curcumin": "COC1=C(C=CC(=C1)/C=C/C(=O)CC(=O)/C=C/C2=CC(=C(C=C2)O)OC)O",
    "Gallic Acid": "C1=C(C=C(C(=C1O)O)O)C(=O)O",
    "Linalool": "CC(=CCCC(C)(C=C)O)C",
    "Rutin": "C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[C@H]([C@@H]([C@H]([C@@H](O2)OC3=C(OC4=CC(=CC(=C4C3=O)O)O)C5=CC(=C(C=C5)O)O)O)O)O)O)O)O",
    "Benzyl Acetate": "CC(=O)OCC1=CC=CC=C1"
}

# Create dataframe
phyto_df = pd.DataFrame(
    list(phytochemicals.items()),
    columns=["Compound", "SMILES"]
)

# Convert SMILES to RDKit molecules
phyto_df["Mol"] = phyto_df["SMILES"].apply(Chem.MolFromSmiles)

print("Total compounds:", len(phyto_df))
print("Valid molecules:", phyto_df["Mol"].notna().sum())

from rdkit.Chem import Descriptors

descriptor_functions = {
    "MolWt": Descriptors.MolWt,
    "LogP": Descriptors.MolLogP,
    "TPSA": Descriptors.TPSA,
    "HBD": Descriptors.NumHDonors,
    "HBA": Descriptors.NumHAcceptors,
    "RotatableBonds": Descriptors.NumRotatableBonds,
    "RingCount": Descriptors.RingCount,
    "HeavyAtomCount": Descriptors.HeavyAtomCount,
}

for name, func in descriptor_functions.items():
    phyto_df[name] = phyto_df["Mol"].apply(func)

print(phyto_df[["Compound"] + list(descriptor_functions.keys())])

# Calculate AD distance of each phytochemical from the training-set centroid

X_phyto = phyto_df[descriptor_cols]

# Standardize using the scaler fitted on the TNF training data
X_phyto_ad = ad_scaler.transform(X_phyto)

# Calculate Euclidean distance from the training-set centroid
phyto_distances = np.linalg.norm(
    X_phyto_ad - train_centroid,
    axis=1
)

phyto_df["AD_Distance"] = phyto_distances

# Determine whether each compound is inside or outside the AD
phyto_df["AD_Status"] = np.where(
    phyto_df["AD_Distance"] <= ad_threshold,
    "Within AD",
    "Outside AD"
)

print(phyto_df[["Compound", "AD_Distance", "AD_Status"]])
print("\nAD Threshold:", ad_threshold)

# Predict pIC50 for the 8 phytochemicals using the final Random Forest model

phyto_df["Predicted_pIC50"] = final_rf.predict(X_phyto)

print(
    phyto_df[
        ["Compound", "Predicted_pIC50", "AD_Distance", "AD_Status"]
    ]
)

# Convert predicted pIC50 to predicted IC50

phyto_df["Predicted_IC50_M"] = 10 ** (-phyto_df["Predicted_pIC50"])
phyto_df["Predicted_IC50_nM"] = phyto_df["Predicted_IC50_M"] * 1e9
phyto_df["Predicted_IC50_uM"] = phyto_df["Predicted_IC50_M"] * 1e6

print(
    phyto_df[
        [
            "Compound",
            "Predicted_pIC50",
            "Predicted_IC50_nM",
            "Predicted_IC50_uM",
            "AD_Status"
        ]
    ].sort_values("Predicted_pIC50", ascending=False)
)

# Create final TNF QSAR results table

final_results = phyto_df[
    [
        "Compound",
        "Predicted_pIC50",
        "Predicted_IC50_nM",
        "Predicted_IC50_uM",
        "AD_Distance",
        "AD_Status"
    ]
].copy()

# Rank compounds according to predicted pIC50
final_results = final_results.sort_values(
    "Predicted_pIC50",
    ascending=False
).reset_index(drop=True)

# Add rank column
final_results.insert(0, "Rank", range(1, len(final_results) + 1))

# Round numerical values for a clean report-ready table
final_results["Predicted_pIC50"] = final_results["Predicted_pIC50"].round(3)
final_results["Predicted_IC50_nM"] = final_results["Predicted_IC50_nM"].round(2)
final_results["Predicted_IC50_uM"] = final_results["Predicted_IC50_uM"].round(3)
final_results["AD_Distance"] = final_results["AD_Distance"].round(3)

print(final_results)

# Save final TNF QSAR results

output_file = "/content/TNF_QSAR_Final_Results.csv"

final_results.to_csv(output_file, index=False)

print("Saved successfully:")
print(output_file)

from google.colab import files
files.download("/content/TNF_QSAR_Final_Results.csv")

print("TNF QSAR session is active")
print("Final RF model:", type(final_rf).__name__)
print("Training compounds:", len(X_train))
print("Test compounds:", len(X_test))
print("Descriptor columns:", descriptor_cols)

# Install PubChemPy for retrieving compound structures
!pip -q install pubchempy

import pubchempy as pcp
import pandas as pd
import time

# Our 60 TNF phytochemicals
phytochemicals = [
    "Quercetin",
    "Curcumin",
    "Resveratrol",
    "Berberine",
    "Epigallocatechin gallate",
    "Ginsenoside Rg1",
    "Ginsenoside Rb1",
    "Mangiferin",
    "Puerarin",
    "Silibinin",
    "Genistein",
    "Myricetin",
    "Apigenin",
    "Luteolin",
    "Kaempferol",
    "Naringenin",
    "Hesperetin",
    "Catechin",
    "Epicatechin",
    "Fisetin",
    "Baicalein",
    "Baicalin",
    "Morin",
    "Chrysin",
    "Galangin",
    "Eriodictyol",
    "Rutin",
    "Naringin",
    "Isoquercitrin",
    "Orientin",
    "Vitexin",
    "Isovitexin",
    "Gallic acid",
    "Caffeic acid",
    "Ferulic acid",
    "Rosmarinic acid",
    "Chlorogenic acid",
    "p-Coumaric acid",
    "Vanillic acid",
    "Sinapic acid",
    "Ellagic acid",
    "Polydatin",
    "Piperine",
    "Palmatine",
    "Jatrorrhizine",
    "Tetrandrine",
    "Harmine",
    "Trigonelline",
    "Capsaicin",
    "Eugenol",
    "Ursolic acid",
    "Oleanolic acid",
    "Betulinic acid",
    "Asiatic acid",
    "Asiaticoside",
    "Madecassoside",
    "Withanolide A",
    "Withaferin A",
    "Thymoquinone",
    "Sulforaphane"
]

results = []

for name in phytochemicals:
    try:
        compounds = pcp.get_compounds(name, "name")

        if compounds:
            c = compounds[0]
            results.append({
                "Compound": name,
                "PubChem_CID": c.cid,
                "SMILES": c.isomeric_smiles
            })
        else:
            results.append({
                "Compound": name,
                "PubChem_CID": None,
                "SMILES": None
            })

    except Exception as e:
        results.append({
            "Compound": name,
            "PubChem_CID": None,
            "SMILES": None
        })

    time.sleep(0.2)

smiles_df = pd.DataFrame(results)

print("Total compounds:", len(smiles_df))
print("SMILES found:", smiles_df["SMILES"].notna().sum())
print("SMILES missing:", smiles_df["SMILES"].isna().sum())

display(smiles_df)

import pubchempy as pcp

polydatin = pcp.get_compounds("Polydatin", "name")

for c in polydatin:
    print("CID:", c.cid)
    print("SMILES:", c.smiles)

polydatin = pcp.get_compounds("resveratrol-3-O-glucoside", "name")

print("Number of results:", len(polydatin))

for c in polydatin:
    print("CID:", c.cid)
    print("SMILES:", c.smiles)

from rdkit import Chem

# Add Polydatin to our dataframe
polydatin_smiles = "C1=CC(=CC=C1/C=C/C2=CC(=CC(=C2)O[C@H]3[C@@H]([C@H]([C@@H]([C@H](O3)CO)O)O)O)O)O"

smiles_df.loc[smiles_df["Compound"] == "Polydatin", "PubChem_CID"] = 5281718
smiles_df.loc[smiles_df["Compound"] == "Polydatin", "SMILES"] = polydatin_smiles

# Validate all SMILES with RDKit
smiles_df["Mol"] = smiles_df["SMILES"].apply(Chem.MolFromSmiles)
smiles_df["Valid_SMILES"] = smiles_df["Mol"].notna()

print("Total compounds:", len(smiles_df))
print("Valid SMILES:", smiles_df["Valid_SMILES"].sum())
print("Invalid SMILES:", (~smiles_df["Valid_SMILES"]).sum())

# Show any invalid structures
display(smiles_df.loc[~smiles_df["Valid_SMILES"], ["Compound", "SMILES"]])

from rdkit.Chem import Descriptors, Crippen, Lipinski

# Calculate the same 8 descriptors used for the TNF QSAR model
smiles_df["MolWt"] = smiles_df["Mol"].apply(Descriptors.MolWt)
smiles_df["LogP"] = smiles_df["Mol"].apply(Crippen.MolLogP)
smiles_df["TPSA"] = smiles_df["Mol"].apply(Descriptors.TPSA)
smiles_df["HBD"] = smiles_df["Mol"].apply(Lipinski.NumHDonors)
smiles_df["HBA"] = smiles_df["Mol"].apply(Lipinski.NumHAcceptors)
smiles_df["RotatableBonds"] = smiles_df["Mol"].apply(Lipinski.NumRotatableBonds)
smiles_df["RingCount"] = smiles_df["Mol"].apply(Lipinski.RingCount)
smiles_df["HeavyAtomCount"] = smiles_df["Mol"].apply(Descriptors.HeavyAtomCount)

# Display the descriptor table
descriptor_cols = [
    "MolWt", "LogP", "TPSA", "HBD", "HBA",
    "RotatableBonds", "RingCount", "HeavyAtomCount"
]

display(smiles_df[["Compound"] + descriptor_cols])

# Predict TNF activity for all 60 phytochemicals

smiles_df["Predicted_pIC50"] = final_rf.predict(
    smiles_df[descriptor_cols]
)

# Convert predicted pIC50 to predicted IC50
smiles_df["Predicted_IC50_nM"] = 10 ** (9 - smiles_df["Predicted_pIC50"])
smiles_df["Predicted_IC50_uM"] = smiles_df["Predicted_IC50_nM"] / 1000

# Display predictions
prediction_cols = [
    "Compound",
    "Predicted_pIC50",
    "Predicted_IC50_nM",
    "Predicted_IC50_uM"
]

display(
    smiles_df[prediction_cols]
    .sort_values("Predicted_pIC50", ascending=False)
    .reset_index(drop=True)
)

# Applicability Domain analysis for the 60 phytochemicals

# Transform the 60 compounds using the SAME scaler fitted on TNF training data
X_phytochemicals_ad = ad_scaler.transform(smiles_df[descriptor_cols])

# Calculate Euclidean distance from the TNF training-set centroid
phytochemical_ad_distances = np.linalg.norm(
    X_phytochemicals_ad - train_centroid,
    axis=1
)

# Add AD distance and status
smiles_df["AD_Distance"] = phytochemical_ad_distances
smiles_df["AD_Status"] = smiles_df["AD_Distance"].apply(
    lambda x: "Within AD" if x <= ad_threshold else "Outside AD"
)

# Count AD results
print("Applicability Domain Results")
print("--------------------------------")
print("Total compounds:", len(smiles_df))
print("Within AD:", (smiles_df["AD_Status"] == "Within AD").sum())
print("Outside AD:", (smiles_df["AD_Status"] == "Outside AD").sum())
print("AD threshold:", ad_threshold)

# Display AD results
display(
    smiles_df[
        ["Compound", "Predicted_pIC50",
         "Predicted_IC50_uM", "AD_Distance", "AD_Status"]
    ]
    .sort_values("Predicted_pIC50", ascending=False)
    .reset_index(drop=True)
)

# Final TNF-QSAR results table for all 60 phytochemicals

final_60 = (
    smiles_df
    .sort_values("Predicted_pIC50", ascending=False)
    .reset_index(drop=True)
)

final_60["Rank"] = final_60.index + 1

final_60_cols = [
    "Rank",
    "Compound",
    "PubChem_CID",
    "Predicted_pIC50",
    "Predicted_IC50_nM",
    "Predicted_IC50_uM",
    "AD_Distance",
    "AD_Status"
]

final_60 = final_60[final_60_cols]

display(final_60)

import pandas as pd

# ============================================
# RANK COMPOUNDS WITHIN APPLICABILITY DOMAIN
# ============================================

# Keep only compounds that are Within AD
within_ad = smiles_df[smiles_df["AD_Status"].str.strip().str.lower() == "within ad"].copy()

# Rank by predicted pIC50 (highest = Rank 1)
within_ad = within_ad.sort_values(
    by="Predicted_pIC50",
    ascending=False
).reset_index(drop=True)

# Create new Within-AD Rank
within_ad.insert(0, "Within_AD_Rank", range(1, len(within_ad) + 1))

# Display important columns
ranking = within_ad[
    [
        "Within_AD_Rank",
        "Compound",
        "PubChem_CID",
        "Predicted_pIC50",
        "Predicted_IC50_nM",
        "Predicted_IC50_uM",
        "AD_Distance",
        "AD_Status"
    ]
]

display(ranking)

output_file = "TNF_QSAR_Within_AD_Ranked.csv"

ranking.to_csv(output_file, index=False)

print(f"Saved: {output_file}")