# -*- coding: utf-8 -*-
"""HEMAT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Lg05js2wRThKuw1i9jRIuXmgzZ5Kx01
"""

!pip install scanpy

# Load the RData file
load("/content/GSE111014_seurat_afterAnno.RData")

# See what objects were loaded
ls()

# Replace 'seurat_obj' with your actual object name
obj <- seurat_obj

# List all assays
Assays(obj)

# Check the default assay
DefaultAssay(obj)

# Print assay information
print(obj@assays)

# Check if an SCT assay exists
if ("SCT" %in% Assays(obj)) {
  cat("SCTransform (SCT) assay is present.\n")
} else {
  cat("No SCT assay found.\n")
}

# Check normalization method in RNA assay
if ("RNA" %in% Assays(obj)) {
  cat("RNA normalization method:",
      obj@assays$RNA@commands$NormalizeData.RNA@params$normalization.method,
      "\n")
}

# Check which assay is currently active
cat("Default assay:", DefaultAssay(obj), "\n")

import scanpy as sc
import anndata as ad

print(sc.__version__)
print(ad.__version__)

import os

print(os.listdir())

import scanpy as sc

adata2 = sc.read_h5ad("/content/GSE111014.h5ad")
print(adata2)

# Python packages
!pip install scanpy anndata pandas numpy rpy2

# R packages
!apt-get update -qq
!apt-get install -y r-base

# Install Seurat in R
!R -e "install.packages('Seurat', repos='https://cloud.r-project.org')"

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# load("GSE111014_seurat_afterAnno.RData")
# ls()

import os

print(os.path.exists("GSE111014_seurat_afterAnno.RData"))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(Seurat)
# library(dplyr)
# library(ggplot2)
# 
# load("GSE111014_seurat_afterAnno.RData")
# 
# ls()

# Commented out IPython magic to ensure Python compatibility.
# %%R
# objects()

# Commented out IPython magic to ensure Python compatibility.
# %%R
# colnames(sceAnalyse@meta.data)
# 
# head(sceAnalyse@meta.data)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# cat("Total Cells =", ncol(sceAnalyse), "\n")
# cat("Total Genes =", nrow(sceAnalyse), "\n")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# colnames(sceAnalyse@meta.data)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# table(sceAnalyse$celltype)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# summary_df <- data.frame(
# Metric = c(
# "Total Cells",
# "Total Genes",
# "Patients",
# "Conditions",
# "Timepoints",
# "Cell Types"
# ),
# 
# Value = c(
# ncol(sceAnalyse),
# nrow(sceAnalyse),
# length(unique(sceAnalyse$patient)),
# length(unique(sceAnalyse$condition)),
# length(unique(sceAnalyse$timepoint)),
# length(unique(sceAnalyse$celltype))
# )
# )
# 
# summary_df

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(ggplot2)
# 
# cell_comp <- as.data.frame(
# table(sceAnalyse$celltype)
# )
# 
# colnames(cell_comp) <- c("CellType","Count")
# 
# ggplot(
# cell_comp,
# aes(
# x = CellType,
# y = Count
# )
# ) +
# geom_bar(stat = "identity") +
# theme_bw() +
# theme(
# axis.text.x =
# element_text(
# angle = 90,
# hjust = 1
# )
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# colnames(sceAnalyse@meta.data)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# head(sceAnalyse@meta.data)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(Seurat)
# library(dplyr)
# library(ggplot2)
# library(RColorBrewer)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# cell_df <- sceAnalyse@meta.data %>%
#   count(celltype) %>%
#   mutate(
#     Percent = round(100*n/sum(n),1)
#   )
# 
# p <- ggplot(
#   cell_df,
#   aes(
#     x=reorder(celltype,Percent),
#     y=Percent,
#     fill=celltype
#   )
# )+
# geom_col(color="black", width=0.8)+
# geom_text(
#   aes(label=paste0(Percent,"%")),
#   hjust=-0.2,
#   size=5,
#   fontface="bold"
# )+
# coord_flip()+
# theme_classic(base_size=16)+
# theme(legend.position="none")+
# labs(
#   title="Cell Type Composition",
#   x="",
#   y="Percentage (%)"
# )
# 
# print(p)
# 
# ggsave(
#   "CellType_Composition.png",
#   plot=p,
#   width=10,
#   height=6,
#   dpi=600
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# prepost_df <- sceAnalyse@meta.data %>%
#   count(timepoint, celltype) %>%
#   group_by(timepoint) %>%
#   mutate(
#     Percent = 100*n/sum(n)
#   )
# 
# p <- ggplot(
#   prepost_df,
#   aes(
#     x=timepoint,
#     y=Percent,
#     fill=celltype
#   )
# )+
# geom_bar(stat="identity")+
# theme_bw(base_size=16)+
# labs(
#   title="Pre vs Post Treatment",
#   x="Timepoint",
#   y="Percentage (%)"
# )
# 
# print(p)
# 
# ggsave(
#   "Pre_Post_CellComposition.png",
#   plot=p,
#   width=8,
#   height=6,
#   dpi=600
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# sens_df <- sceAnalyse@meta.data %>%
#   count(condition, celltype) %>%
#   group_by(condition) %>%
#   mutate(
#     Percent = 100*n/sum(n)
#   )
# 
# p <- ggplot(
#   sens_df,
#   aes(
#     x=condition,
#     y=Percent,
#     fill=celltype
#   )
# )+
# geom_bar(stat="identity")+
# theme_bw(base_size=16)+
# labs(
#   title="Sensitive vs Resistant",
#   x="Condition",
#   y="Percentage (%)"
# )
# 
# print(p)
# 
# ggsave(
#   "Sensitive_Resistant.png",
#   plot=p,
#   width=8,
#   height=6,
#   dpi=600
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# patient_df <- sceAnalyse@meta.data %>%
#   count(patient, celltype) %>%
#   group_by(patient) %>%
#   mutate(
#     Percent = 100*n/sum(n)
#   )
# 
# p <- ggplot(
#   patient_df,
#   aes(
#     x=patient,
#     y=Percent,
#     fill=celltype
#   )
# )+
# geom_bar(stat="identity")+
# theme_bw(base_size=16)+
# labs(
#   title="Patient-wise Cell Composition",
#   y="Percentage (%)"
# )
# 
# print(p)
# 
# ggsave(
#   "Patient_Composition.png",
#   plot=p,
#   width=10,
#   height=6,
#   dpi=600
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# cd8_df <- sceAnalyse@meta.data %>%
#   mutate(
#     CD8 = ifelse(
#       celltype=="CD8+ T cells",
#       "CD8 T cells",
#       "Other"
#     )
#   ) %>%
#   count(timepoint, CD8) %>%
#   group_by(timepoint) %>%
#   mutate(
#     Percent=100*n/sum(n)
#   ) %>%
#   filter(CD8=="CD8 T cells")
# 
# p <- ggplot(
#   cd8_df,
#   aes(
#     x=timepoint,
#     y=Percent,
#     fill=timepoint
#   )
# )+
# geom_col(width=0.7)+
# geom_text(
#   aes(label=round(Percent,1)),
#   vjust=-0.3,
#   size=5
# )+
# theme_classic(base_size=16)+
# labs(
#   title="CD8 T Cells",
#   y="Percentage (%)"
# )
# 
# print(p)
# 
# ggsave(
#   "CD8_Tcell_Change.png",
#   plot=p,
#   width=7,
#   height=5,
#   dpi=600
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# patient_time_df <- sceAnalyse@meta.data %>%
#   count(patient, timepoint, celltype) %>%
#   group_by(patient, timepoint) %>%
#   mutate(
#     Percent = 100*n/sum(n)
#   )
# 
# patient_time_df$Patient_Time <- paste(
#   patient_time_df$patient,
#   patient_time_df$timepoint,
#   sep="_"
# )
# 
# cell_colors <- c(
#   "Malignant cells"="#F44336",
#   "CD8+ T cells"="#1976D2",
#   "Mono/Macro"="#E76AB3",
#   "CD4+ T cells"="#6EC1E4",
#   "NK cells"="#39B54A"
# )
# 
# p <- ggplot(
#   patient_time_df,
#   aes(
#     x=Patient_Time,
#     y=Percent,
#     fill=celltype
#   )
# )+
# geom_bar(
#   stat="identity",
#   width=0.8
# )+
# scale_fill_manual(
#   values=cell_colors
# )+
# theme_bw(base_size=16)+
# theme(
#   axis.text.x=element_text(
#     angle=45,
#     hjust=1,
#     face="bold"
#   ),
#   legend.title=element_blank()
# )+
# labs(
#   title="Patient-wise Pre/Post Cell Composition",
#   x="Patient and Timepoint",
#   y="Cell Percentage (%)"
# )
# 
# print(p)
# 
# ggsave(
#   "Patient_PrePost_Composition.png",
#   plot=p,
#   dpi=600,
#   width=12,
#   height=7
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# p <- ggplot(
#   patient_time_df,
#   aes(
#     x=Patient_Time,
#     y=Percent,
#     fill=celltype
#   )
# )+
# geom_bar(
#   stat="identity",
#   position="fill"
# )+
# scale_fill_manual(
#   values=cell_colors
# )+
# scale_y_continuous(
#   labels=scales::percent_format()
# )+
# theme_classic(base_size=16)+
# theme(
#   axis.text.x=element_text(
#     angle=45,
#     hjust=1
#   )
# )+
# labs(
#   title="Relative Cell Composition Across Patients",
#   x="Patient and Timepoint",
#   y="Relative Abundance"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# cell_colors <- c(
#   "Malignant cells" = "#F44336",
#   "CD8+ T cells"    = "#1976D2",
#   "Mono/Macro"      = "#E76AB3",
#   "CD4+ T cells"    = "#6EC1E4",
#   "NK cells"        = "#39B54A"
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# library(scales)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# cell_colors <- c(
#   "Malignant cells"="#F44336",
#   "CD8+ T cells"="#1976D2",
#   "Mono/Macro"="#E76AB3",
#   "CD4+ T cells"="#6EC1E4",
#   "NK cells"="#39B54A"
# )
# 
# sens_df <- sceAnalyse@meta.data %>%
#   count(condition, celltype) %>%
#   group_by(condition) %>%
#   mutate(
#     Percent = round(100*n/sum(n),1)
#   )
# 
# p <- ggplot(
#   sens_df,
#   aes(
#     x = condition,
#     y = Percent,
#     fill = celltype
#   )
# ) +
# geom_col() +
# 
# geom_text(
#   aes(label = paste0(Percent,"%")),
#   position = position_stack(vjust = 0.5),
#   color = "white",
#   fontface = "bold",
#   size = 4
# ) +
# 
# scale_fill_manual(values = cell_colors) +
# 
# theme_classic(base_size = 16) +
# 
# labs(
#   title = "Sensitive vs Resistant",
#   x = "",
#   y = "Percentage (%)"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# prepost_df <- sceAnalyse@meta.data %>%
#   count(timepoint, celltype) %>%
#   group_by(timepoint) %>%
#   mutate(
#     Percent = round(100*n/sum(n),1)
#   )
# 
# p <- ggplot(
#   prepost_df,
#   aes(
#     x = timepoint,
#     y = Percent,
#     fill = celltype
#   )
# ) +
# geom_col() +
# 
# geom_text(
#   aes(label = paste0(Percent,"%")),
#   position = position_stack(vjust = 0.5),
#   color = "white",
#   fontface = "bold",
#   size = 4
# ) +
# 
# scale_fill_manual(values = cell_colors) +
# 
# theme_classic(base_size = 16) +
# 
# labs(
#   title = "Pre vs Post Treatment",
#   x = "",
#   y = "Percentage (%)"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# patient_df <- sceAnalyse@meta.data %>%
#   count(patient, timepoint, celltype) %>%
#   group_by(patient, timepoint) %>%
#   mutate(
#     Percent = round(100*n/sum(n),1)
#   )
# 
# patient_df$Patient_Time <- paste(
#   patient_df$patient,
#   patient_df$timepoint,
#   sep = "_"
# )
# 
# p <- ggplot(
#   patient_df,
#   aes(
#     x = Patient_Time,
#     y = Percent,
#     fill = celltype
#   )
# ) +
# geom_col() +
# 
# geom_text(
#   aes(label = ifelse(Percent > 5,
#                      paste0(Percent,"%"),
#                      "")),
#   position = position_stack(vjust = 0.5),
#   color = "white",
#   fontface = "bold",
#   size = 3.5
# ) +
# 
# scale_fill_manual(values = cell_colors) +
# 
# theme_classic(base_size = 16) +
# 
# theme(
#   axis.text.x = element_text(
#     angle = 45,
#     hjust = 1,
#     face = "bold"
#   )
# ) +
# 
# labs(
#   title = "Patient-wise Pre/Post Composition",
#   x = "",
#   y = "Percentage (%)"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# cd8_df <- sceAnalyse@meta.data %>%
#   mutate(
#     CD8 = celltype == "CD8+ T cells"
#   ) %>%
#   group_by(patient, timepoint) %>%
#   summarise(
#     Percent = round(100*mean(CD8),1),
#     .groups = "drop"
#   )
# 
# p <- ggplot(
#   cd8_df,
#   aes(
#     x = patient,
#     y = Percent,
#     fill = timepoint
#   )
# ) +
# geom_col(
#   position = position_dodge(0.8),
#   width = 0.7
# ) +
# 
# geom_text(
#   aes(label = paste0(Percent,"%")),
#   position = position_dodge(0.8),
#   vjust = -0.4,
#   fontface = "bold",
#   size = 5
# ) +
# 
# scale_fill_manual(
#   values = c(
#     "pre" = "#1976D2",
#     "post" = "#6EC1E4"
#   )
# ) +
# 
# theme_classic(base_size = 16) +
# 
# labs(
#   title = "CD8+ T-cell Frequency by Patient",
#   x = "Patient",
#   y = "Percentage (%)"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# cd4_df <- sceAnalyse@meta.data %>%
#   mutate(
#     CD4 = celltype == "CD4+ T cells"
#   ) %>%
#   group_by(patient, timepoint) %>%
#   summarise(
#     Percent = round(100 * mean(CD4), 1),
#     .groups = "drop"
#   )
# 
# p <- ggplot(
#   cd4_df,
#   aes(
#     x = patient,
#     y = Percent,
#     fill = timepoint
#   )
# ) +
# geom_col(
#   position = position_dodge(0.8),
#   width = 0.7
# ) +
# 
# geom_text(
#   aes(label = paste0(Percent, "%")),
#   position = position_dodge(0.8),
#   vjust = -0.4,
#   fontface = "bold",
#   size = 5
# ) +
# 
# scale_fill_manual(
#   values = c(
#     "pre" = "#6EC1E4",
#     "post" = "#1976D2"
#   )
# ) +
# 
# theme_classic(base_size = 16) +
# 
# labs(
#   title = "CD4+ T-cell Frequency by Patient",
#   x = "Patient",
#   y = "Percentage (%)",
#   fill = "Timepoint"
# )
# 
# print(p)
# 
# ggsave(
#   "CD4_Tcell_Frequency_ByPatient.png",
#   plot = p,
#   width = 8,
#   height = 6,
#   dpi = 600
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# cd4_overall <- sceAnalyse@meta.data %>%
#   mutate(
#     CD4 = celltype == "CD4+ T cells"
#   ) %>%
#   group_by(timepoint) %>%
#   summarise(
#     Percent = round(100 * mean(CD4), 1),
#     .groups = "drop"
#   )
# 
# p <- ggplot(
#   cd4_overall,
#   aes(
#     x = timepoint,
#     y = Percent,
#     fill = timepoint
#   )
# ) +
# geom_col(
#   width = 0.65
# ) +
# 
# geom_text(
#   aes(label = paste0(Percent, "%")),
#   vjust = -0.4,
#   size = 6,
#   fontface = "bold"
# ) +
# 
# scale_fill_manual(
#   values = c(
#     "pre" = "#6EC1E4",
#     "post" = "#1976D2"
#   )
# ) +
# 
# theme_classic(base_size = 16) +
# 
# labs(
#   title = "Overall CD4+ T-cell Abundance",
#   x = "",
#   y = "Percentage (%)"
# )
# 
# print(p)
# 
# ggsave(
#   "CD4_PrePost_Overall.png",
#   plot = p,
#   width = 7,
#   height = 5,
#   dpi = 600
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# tcell_df <- sceAnalyse@meta.data %>%
#   filter(celltype %in% c("CD4+ T cells","CD8+ T cells")) %>%
#   count(timepoint, celltype) %>%
#   group_by(timepoint) %>%
#   mutate(
#     Percent = round(100 * n / sum(n), 1)
#   )
# 
# p <- ggplot(
#   tcell_df,
#   aes(
#     x = timepoint,
#     y = Percent,
#     fill = celltype
#   )
# ) +
# geom_col(
#   position = "dodge"
# ) +
# 
# geom_text(
#   aes(label = paste0(Percent, "%")),
#   position = position_dodge(0.9),
#   vjust = -0.4,
#   size = 5,
#   fontface = "bold"
# ) +
# 
# scale_fill_manual(
#   values = c(
#     "CD8+ T cells" = "#1976D2",
#     "CD4+ T cells" = "#6EC1E4"
#   )
# ) +
# 
# theme_classic(base_size = 16) +
# 
# labs(
#   title = "CD4+ vs CD8+ T-cell Composition",
#   x = "Timepoint",
#   y = "Percentage (%)"
# )
# 
# print(p)
# 
# ggsave(
#   "CD4_CD8_Comparison.png",
#   plot = p,
#   width = 8,
#   height = 6,
#   dpi = 600
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# cd8_df <- sceAnalyse@meta.data %>%
#   mutate(
#     CD8 = celltype == "CD8+ T cells"
#   ) %>%
#   group_by(patient, timepoint) %>%
#   summarise(
#     Percent = round(100 * mean(CD8), 1),
#     .groups = "drop"
#   )
# 
# p <- ggplot(
#   cd8_df,
#   aes(
#     x = patient,
#     y = Percent,
#     fill = timepoint
#   )
# ) +
# geom_col(
#   position = position_dodge(0.8),
#   width = 0.7
# ) +
# geom_text(
#   aes(label = paste0(Percent, "%")),
#   position = position_dodge(0.8),
#   vjust = -0.4,
#   size = 5,
#   fontface = "bold"
# ) +
# scale_fill_manual(
#   values = c(
#     "pre" = "#1976D2",
#     "post" = "#6EC1E4"
#   )
# ) +
# theme_classic(base_size = 16) +
# labs(
#   title = "CD8+ T-cell Frequency by Patient",
#   x = "Patient",
#   y = "Percentage (%)",
#   fill = "Timepoint"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# cd4_df <- sceAnalyse@meta.data %>%
#   mutate(
#     CD4 = celltype == "CD4+ T cells"
#   ) %>%
#   group_by(patient, timepoint) %>%
#   summarise(
#     Percent = round(100 * mean(CD4), 1),
#     .groups = "drop"
#   )
# 
# p <- ggplot(
#   cd4_df,
#   aes(
#     x = patient,
#     y = Percent,
#     fill = timepoint
#   )
# ) +
# geom_col(
#   position = position_dodge(0.8),
#   width = 0.7
# ) +
# geom_text(
#   aes(label = paste0(Percent, "%")),
#   position = position_dodge(0.8),
#   vjust = -0.4,
#   size = 5,
#   fontface = "bold"
# ) +
# scale_fill_manual(
#   values = c(
#     "pre" = "#1976D2",
#     "post" = "#6EC1E4"
#   )
# ) +
# theme_classic(base_size = 16) +
# labs(
#   title = "CD4+ T-cell Frequency by Patient",
#   x = "Patient",
#   y = "Percentage (%)",
#   fill = "Timepoint"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# tcell_df <- sceAnalyse@meta.data %>%
#   filter(celltype %in% c("CD4+ T cells","CD8+ T cells")) %>%
#   count(timepoint, celltype) %>%
#   group_by(timepoint) %>%
#   mutate(
#     Percent = round(100*n/sum(n),1)
#   )
# 
# p <- ggplot(
#   tcell_df,
#   aes(
#     x = celltype,
#     y = Percent,
#     fill = timepoint
#   )
# ) +
# geom_col(
#   position = position_dodge(0.8),
#   width = 0.7
# ) +
# geom_text(
#   aes(label = paste0(Percent,"%")),
#   position = position_dodge(0.8),
#   vjust = -0.4,
#   size = 5,
#   fontface = "bold"
# ) +
# scale_fill_manual(
#   values = c(
#     "pre" = "#1976D2",
#     "post" = "#6EC1E4"
#   )
# ) +
# theme_classic(base_size = 16) +
# labs(
#   title = "CD4+ and CD8+ T-cell Changes After Treatment",
#   x = "",
#   y = "Percentage (%)",
#   fill = "Timepoint"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# tcell_df <- sceAnalyse@meta.data %>%
#   filter(celltype %in% c("CD4+ T cells","CD8+ T cells")) %>%
#   count(patient, timepoint, celltype) %>%
#   group_by(patient, timepoint) %>%
#   mutate(
#     Percent = 100*n/sum(n)
#   )
# 
# p <- ggplot(
#   tcell_df,
#   aes(
#     x = timepoint,
#     y = Percent,
#     group = patient,
#     color = patient
#   )
# ) +
# 
# geom_line(
#   linewidth = 1.2
# ) +
# 
# geom_point(
#   size = 4
# ) +
# 
# geom_text(
#   aes(
#     label = round(Percent,1)
#   ),
#   nudge_y = 2,
#   size = 4
# ) +
# 
# facet_wrap(
#   ~celltype
# ) +
# 
# theme_classic(base_size = 16) +
# 
# labs(
#   title = "Patient-specific Changes After Treatment",
#   x = "",
#   y = "Percentage (%)"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# tcell_df <- sceAnalyse@meta.data %>%
#   filter(celltype %in% c("CD4+ T cells","CD8+ T cells")) %>%
#   count(patient, timepoint, celltype) %>%
#   group_by(patient, timepoint) %>%
#   mutate(
#     Percent = round(100*n/sum(n),1)
#   )
# 
# p <- ggplot(
#   tcell_df,
#   aes(
#     x = patient,
#     y = Percent,
#     fill = timepoint
#   )
# ) +
# 
# geom_col(
#   position = position_dodge(width = 0.8),
#   width = 0.7
# ) +
# 
# geom_text(
#   aes(label = paste0(Percent,"%")),
#   position = position_dodge(width = 0.8),
#   vjust = -0.4,
#   size = 4.5,
#   fontface = "bold"
# ) +
# 
# facet_wrap(
#   ~celltype,
#   nrow = 1
# ) +
# 
# scale_fill_manual(
#   values = c(
#     "pre"  = "#1976D2",
#     "post" = "#6EC1E4"
#   )
# ) +
# 
# theme_classic(base_size = 16) +
# 
# theme(
#   strip.text = element_text(
#     size = 16,
#     face = "bold"
#   ),
#   legend.position = "top"
# ) +
# 
# labs(
#   title = "Patient-wise CD4+ and CD8+ T-cell Frequencies",
#   subtitle = "Pre-treatment vs Post-treatment",
#   x = "Patient",
#   y = "Percentage (%)",
#   fill = "Timepoint"
# )
# 
# print(p)
# 
# ggsave(
#   "Patient_CD4_CD8_Combined.png",
#   plot = p,
#   width = 12,
#   height = 6,
#   dpi = 600
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# cell_colors <- c(
#   "Malignant cells"="#F44336",
#   "CD8+ T cells"="#1976D2",
#   "Mono/Macro"="#E76AB3",
#   "CD4+ T cells"="#6EC1E4",
#   "NK cells"="#39B54A"
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# cell_colors <- c(
#   "Malignant cells"="#F44336",
#   "CD8+ T cells"="#1976D2",
#   "Mono/Macro"="#E76AB3",
#   "CD4+ T cells"="#6EC1E4",
#   "NK cells"="#39B54A"
# )
# 
# comp_df <- sceAnalyse@meta.data %>%
#   count(condition, timepoint, celltype) %>%
#   group_by(condition, timepoint) %>%
#   mutate(
#     Percent = round(100*n/sum(n),1)
#   )
# 
# p <- ggplot(
#   comp_df,
#   aes(
#     x=timepoint,
#     y=Percent,
#     fill=celltype
#   )
# )+
# geom_col()+
# 
# geom_text(
#   aes(
#     label=ifelse(
#       Percent > 5,
#       paste0(Percent,"%"),
#       ""
#     )
#   ),
#   position=position_stack(vjust=0.5),
#   color="white",
#   size=4,
#   fontface="bold"
# )+
# 
# facet_wrap(
#   ~condition,
#   nrow=1
# )+
# 
# scale_fill_manual(
#   values=cell_colors
# )+
# 
# theme_classic(base_size=16)+
# 
# labs(
#   title="Cell-Type Composition Before and After Treatment",
#   subtitle="Sensitive vs Resistant Patients",
#   x="Treatment Timepoint",
#   y="Percentage (%)"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# cell_colors <- c(
#   "Malignant cells"="#F44336",
#   "CD8+ T cells"="#1976D2",
#   "Mono/Macro"="#E76AB3",
#   "CD4+ T cells"="#6EC1E4",
#   "NK cells"="#39B54A"
# )
# 
# comp_df <- sceAnalyse@meta.data %>%
#   count(condition, timepoint, celltype) %>%
#   group_by(condition, timepoint) %>%
#   mutate(
#     Percent = round(100*n/sum(n),1)
#   )
# 
# p <- ggplot(
#   comp_df,
#   aes(
#     x=timepoint,
#     y=Percent,
#     fill=celltype
#   )
# )+
# geom_col()+
# 
# geom_text(
#   aes(
#     label=ifelse(
#       Percent > 5,
#       paste0(Percent,"%"),
#       ""
#     )
#   ),
#   position=position_stack(vjust=0.5),
#   color="white",
#   size=4,
#   fontface="bold"
# )+
# 
# facet_wrap(
#   ~condition,
#   nrow=1
# )+
# 
# scale_fill_manual(
#   values=cell_colors
# )+
# 
# theme_classic(base_size=16)+
# 
# labs(
#   title="Cell-Type Composition Before and After Treatment",
#   subtitle="Sensitive vs Resistant Patients",
#   x="Treatment Timepoint",
#   y="Percentage (%)"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# cd8_df <- sceAnalyse@meta.data %>%
#   mutate(CD8 = celltype == "CD8+ T cells") %>%
#   group_by(patient, timepoint) %>%
#   summarise(
#     Percent = round(100 * mean(CD8), 1),
#     .groups = "drop"
#   )
# 
# p <- ggplot(
#   cd8_df,
#   aes(
#     x = patient,
#     y = Percent,
#     fill = timepoint
#   )
# ) +
# geom_col(
#   position = position_dodge(0.8),
#   width = 0.7
# ) +
# geom_text(
#   aes(label = paste0(Percent,"%")),
#   position = position_dodge(0.8),
#   vjust = -0.4,
#   size = 5,
#   fontface = "bold"
# ) +
# scale_fill_manual(
#   values = c(
#     "pre"="#1976D2",
#     "post"="#6EC1E4"
#   )
# ) +
# theme_classic(base_size=16) +
# labs(
#   title="CD8+ T Cells by Patient",
#   y="Percentage (%)",
#   fill="Timepoint"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# cd8_df <- sceAnalyse@meta.data %>%
#   mutate(CD8 = celltype == "CD8+ T cells") %>%
#   group_by(patient,timepoint) %>%
#   summarise(
#     Percent = 100*mean(CD8),
#     .groups="drop"
#   )
# 
# p <- ggplot(
#   cd8_df,
#   aes(
#     x=timepoint,
#     y=Percent,
#     group=patient,
#     color=patient
#   )
# )+
# geom_line(linewidth=1.3)+
# geom_point(size=4)+
# geom_text(
#   aes(label=round(Percent,1)),
#   nudge_y=2
# )+
# theme_classic(base_size=16)+
# labs(
#   title="CD8+ T Cell Change Per Patient",
#   y="Percentage (%)"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# cd4_df <- sceAnalyse@meta.data %>%
#   mutate(CD4 = celltype == "CD4+ T cells") %>%
#   group_by(patient,timepoint) %>%
#   summarise(
#     Percent = round(100*mean(CD4),1),
#     .groups="drop"
#   )
# 
# p <- ggplot(
#   cd4_df,
#   aes(
#     x=patient,
#     y=Percent,
#     fill=timepoint
#   )
# )+
# geom_col(
#   position=position_dodge(0.8),
#   width=0.7
# )+
# geom_text(
#   aes(label=paste0(Percent,"%")),
#   position=position_dodge(0.8),
#   vjust=-0.4,
#   size=5
# )+
# scale_fill_manual(
#   values=c(
#     "pre"="#1976D2",
#     "post"="#6EC1E4"
#   )
# )+
# theme_classic(base_size=16)+
# labs(
#   title="CD4+ T Cells by Patient",
#   y="Percentage (%)"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# mal_df <- sceAnalyse@meta.data %>%
#   mutate(
#     Malignant = celltype == "Malignant cells"
#   ) %>%
#   group_by(patient, timepoint) %>%
#   summarise(
#     Percent = round(100 * mean(Malignant), 1),
#     .groups = "drop"
#   )
# 
# p <- ggplot(
#   mal_df,
#   aes(
#     x = patient,
#     y = Percent,
#     fill = timepoint
#   )
# ) +
# geom_col(
#   position = position_dodge(0.8),
#   width = 0.7
# ) +
# geom_text(
#   aes(label = paste0(Percent,"%")),
#   position = position_dodge(0.8),
#   vjust = -0.4,
#   size = 5,
#   fontface = "bold"
# ) +
# scale_fill_manual(
#   values = c(
#     "pre" = "#1976D2",
#     "post" = "#6EC1E4"
#   )
# ) +
# theme_classic(base_size = 16) +
# labs(
#   title = "Malignant Cell Frequency by Patient",
#   x = "Patient",
#   y = "Percentage (%)",
#   fill = "Timepoint"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# scale_fill_manual(
#   values = c(
#     "pre"  = "#F44336",
#     "post" = "#FF8A80"
#   )
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# "Malignant cells" = "#F44336"

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(dplyr)
# library(ggplot2)
# 
# mal_df <- sceAnalyse@meta.data %>%
#   mutate(
#     Malignant = celltype == "Malignant cells"
#   ) %>%
#   group_by(patient, timepoint) %>%
#   summarise(
#     Percent = round(100 * mean(Malignant), 1),
#     .groups = "drop"
#   )
# 
# p <- ggplot(
#   mal_df,
#   aes(
#     x = patient,
#     y = Percent,
#     fill = timepoint
#   )
# ) +
# geom_col(
#   position = position_dodge(0.8),
#   width = 0.7
# ) +
# geom_text(
#   aes(label = paste0(Percent,"%")),
#   position = position_dodge(0.8),
#   vjust = -0.4,
#   size = 5,
#   fontface = "bold"
# ) +
# scale_fill_manual(
#   values = c(
#     "pre" = "#1976D2",
#     "post" = "#6EC1E4"
#   )
# ) +
# theme_classic(base_size = 16) +
# labs(
#   title = "Malignant Cell Frequency by Patient",
#   x = "Patient",
#   y = "Percentage (%)",
#   fill = "Timepoint"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# mal_df <- sceAnalyse@meta.data %>%
#   mutate(
#     Malignant = celltype == "Malignant cells"
#   ) %>%
#   group_by(patient, timepoint) %>%
#   summarise(
#     Percent = 100 * mean(Malignant),
#     .groups = "drop"
#   )
# 
# p <- ggplot(
#   mal_df,
#   aes(
#     x = timepoint,
#     y = Percent,
#     group = patient,
#     color = patient
#   )
# ) +
# geom_line(linewidth = 1.3) +
# geom_point(size = 4) +
# geom_text(
#   aes(label = round(Percent,1)),
#   nudge_y = 2,
#   size = 4
# ) +
# theme_classic(base_size = 16) +
# labs(
#   title = "Malignant Cell Change Per Patient",
#   x = "",
#   y = "Percentage (%)"
# )
# 
# print(p)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# table(sceAnalyse$celltype)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# Tcells <- subset(
#   sceAnalyse,
#   subset = celltype %in%
#     c(
#       "CD4+ T cells",
#       "CD8+ T cells"
#     )
# )
# 
# Tcells

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# round(
#   prop.table(
#     table(sceAnalyse$celltype)
#   )*100,
#   2
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# table(sceAnalyse$celltype)
# 
# tcells <- subset(
#   sceAnalyse,
#   subset = celltype %in%
#     c(
#       "CD4+ T cells",
#       "CD8+ T cells"
#     )
# )
# 
# cat(
#   "Total T cells =",
#   ncol(tcells),
#   "\n"
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# table(
#   tcells$celltype
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# round(
#   prop.table(
#     table(
#       tcells$celltype
#     )
#   )*100,
#   2
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(Seurat)
# 
# Tcells <- RunPCA(
#   Tcells,
#   npcs = 30,
#   verbose = FALSE
# )
# 
# Tcells <- FindNeighbors(
#   Tcells,
#   dims = 1:30
# )
# 
# Tcells <- FindClusters(
#   Tcells,
#   resolution = 0.5
# )
# 
# Tcells <- RunUMAP(
#   Tcells,
#   dims = 1:30
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# Tcells <- subset(
#   sceAnalyse,
#   subset = celltype %in% c("CD4+ T cells", "CD8+ T cells")
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# dim(Tcells)
# table(Tcells$celltype)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# Tcells <- NormalizeData(Tcells)
# Tcells <- FindVariableFeatures(Tcells)
# Tcells <- ScaleData(Tcells)
# 
# Tcells <- RunPCA(Tcells, npcs = 30)
# 
# Tcells <- FindNeighbors(Tcells, dims = 1:30)
# 
# Tcells <- FindClusters(Tcells, resolution = 0.5)
# 
# Tcells <- RunUMAP(Tcells, dims = 1:30)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# DimPlot(
#   Tcells,
#   reduction = "umap",
#   group.by = "celltype",
#   label = TRUE,
#   repel = TRUE,
#   pt.size = 1
# ) +
# scale_color_manual(
#   values = c(
#     "CD4+ T cells" = "#6EC1E4",
#     "CD8+ T cells" = "#1976D2"
#   )
# ) +
# theme_classic(base_size = 16)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# DimPlot(
#   Tcells,
#   reduction = "umap",
#   group.by = "timepoint",
#   pt.size = 1
# ) +
# scale_color_manual(
#   values = c(
#     "pre" = "#1976D2",
#     "post" = "#6EC1E4"
#   )
# ) +
# theme_classic(base_size = 16)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# DimPlot(
#   Tcells,
#   reduction = "umap",
#   group.by = "condition",
#   pt.size = 1
# ) +
# scale_color_manual(
#   values = c(
#     "sensitive" = "#1976D2",
#     "resistant" = "#F44336"
#   )
# ) +
# theme_classic(base_size = 16)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# DimPlot(
#   sceAnalyse,
#   group.by = "celltype",
#   cells.highlight = WhichCells(
#     sceAnalyse,
#     expression = celltype %in% c("CD4+ T cells", "CD8+ T cells")
#   ),
#   cols = "grey80",
#   cols.highlight = c("#6EC1E4", "#1976D2"),
#   pt.size = 0.5
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# Tcells <- NormalizeData(Tcells)
# Tcells <- FindVariableFeatures(Tcells)
# Tcells <- ScaleData(Tcells)
# Tcells <- RunPCA(Tcells)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# Tcells <- FindNeighbors(Tcells, dims = 1:20)
# Tcells <- FindClusters(Tcells, resolution = 0.4)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# Tcells <- RunUMAP(Tcells, dims = 1:20)
# DimPlot(Tcells, group.by = "seurat_clusters", label = TRUE)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# Tcells <- subset(sceAnalyse, subset = celltype %in% c("CD4+ T cells", "CD8+ T cells"))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# Tcells <- NormalizeData(Tcells)
# Tcells <- FindVariableFeatures(Tcells)
# Tcells <- ScaleData(Tcells)
# Tcells <- RunPCA(Tcells)
# 
# Tcells <- FindNeighbors(Tcells, dims = 1:20)
# Tcells <- FindClusters(Tcells, resolution = 0.4)
# Tcells <- RunUMAP(Tcells, dims = 1:20)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# Tcells$T_subtype <- "Unknown"
# 
# Tcells$T_subtype[WhichCells(Tcells, expression = CD4 > 0 & CD8A == 0)] <- "CD4 T cells"
# Tcells$T_subtype[WhichCells(Tcells, expression = CD8A > 0)] <- "CD8 T cells"

# Commented out IPython magic to ensure Python compatibility.
# %%R
# DimPlot(
#   Tcells,
#   reduction = "umap",
#   group.by = "T_subtype",
#   label = TRUE,
#   repel = TRUE
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(ggplot2)
# library(ggrepel)
# 
# umap_coords <- Embeddings(Tcells, reduction = "umap")
# cluster_info <- Tcells@meta.data$seurat_clusters
# 
# umap_df <- data.frame(
#   UMAP_1 = umap_coords[, 1],
#   UMAP_2 = umap_coords[, 2],
#   cluster = cluster_info
# )
# 
# ggplot(umap_df, aes(x = UMAP_1, y = UMAP_2)) +
#   # cells
#   geom_point(aes(color = cluster), size = 0.6, alpha = 0.7) +
# 
#   # cluster labels (with repelling + background box)
#   geom_label_repel(
#     data = aggregate(cbind(UMAP_1, UMAP_2) ~ cluster, umap_df, median),
#     aes(label = cluster),
#     size = 5,
#     fontface = "bold",
#     box.padding = 0.5,
#     point.padding = 0.3,
#     label.size = 0.4,
#     fill = "white",
#     color = "black",
#     alpha = 0.85
#   ) +
# 
#   theme_classic() +
#   labs(title = "T-cell UMAP (CD4 vs CD8)") +
#   theme(
#     plot.title = element_text(face = "bold", hjust = 0.5)
#   )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# # Calculate mitochondrial percentage
# sceAnalyse[["percent.mt"]] <- PercentageFeatureSet(
#   sceAnalyse,
#   pattern = "^MT-"
# )
# 
# # QC filtering
# sceAnalyse <- subset(
#   sceAnalyse,
#   subset =
#     nFeature_RNA > 200 &
#     nCount_RNA > 200 &
#     percent.mt < 10
# )
# 
# # Number of cells after QC
# cat("Cells after QC filtering:", ncol(sceAnalyse), "\n")
# 
# # Number of genes after QC
# cat("Genes after QC filtering:", nrow(sceAnalyse), "\n")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# # Extract CD4 and CD8 T cells
# Tcells <- subset(
#   sceAnalyse,
#   subset = celltype %in% c("CD4+ T cells", "CD8+ T cells")
# )
# 
# # Number of T cells
# cat("Number of T cells:", ncol(Tcells), "\n")
# 
# # Number of genes in T-cell object
# cat("Number of genes in T-cell object:", nrow(Tcells), "\n")
# 
# # Normalization and downstream analysis
# Tcells <- NormalizeData(Tcells)
# Tcells <- FindVariableFeatures(Tcells, selection.method = "vst", nfeatures = 2000)
# 
# # Number of highly variable genes
# cat("Variable genes selected:", length(VariableFeatures(Tcells)), "\n")
# 
# Tcells <- ScaleData(Tcells)
# Tcells <- RunPCA(Tcells)
# 
# Tcells <- FindNeighbors(Tcells, dims = 1:20)
# Tcells <- FindClusters(Tcells, resolution = 0.4)
# Tcells <- RunUMAP(Tcells, dims = 1:20)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# # To get sceAnalyse_raw, you would typically save the object before QC.
# # Since it's not present, we will assume sceAnalyse before QC was intended for 'raw'.
# # Or, if 'sceAnalyse_raw' was meant to be the initially loaded object,
# # it should have been explicitly assigned before QC steps that modify 'sceAnalyse'.
# # For now, if you want to compare, you'd need to re-run the loading and save an original copy.
# # Let's adjust this to only display available objects to avoid the error.
# 
# cat("Cells after QC:", ncol(sceAnalyse), "\n")
# cat("Genes after QC:", nrow(sceAnalyse), "\n")
# 
# cat("T cells retained:", ncol(Tcells), "\n")
# cat("Genes in T-cell object:", nrow(Tcells), "\n")
# cat("Variable genes:", length(VariableFeatures(Tcells)), "\n")
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# VlnPlot(
#   sceAnalyse,
#   features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
#   ncol = 3,
#   pt.size = 0.1
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# FeatureScatter(
#   sceAnalyse,
#   feature1 = "nCount_RNA",
#   feature2 = "nFeature_RNA"
# )
# 
# FeatureScatter(
#   sceAnalyse,
#   feature1 = "nCount_RNA",
#   feature2 = "percent.mt"
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# DimPlot(
#   Tcells,
#   reduction = "umap",
#   label = TRUE,
#   repel = TRUE
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# DimPlot(
#   Tcells,
#   reduction = "umap",
#   group.by = "celltype"
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(ggplot2)
# 
# cell_counts <- as.data.frame(table(Tcells$celltype))
# colnames(cell_counts) <- c("CellType", "Count")
# 
# ggplot(cell_counts,
#        aes(x = CellType, y = Count)) +
#   geom_bar(stat = "identity") +
#   theme_classic() +
#   labs(title = "T Cell Composition")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# # The object 'sceAnalyse_raw' was not created in this session.
# # Removing the lines that reference it to avoid the error.
# 
# cat("Cells after QC:", ncol(sceAnalyse), "\n")
# cat("Genes after QC:", nrow(sceAnalyse), "\n")
# 
# cat("T cells retained:", ncol(Tcells), "\n")
# cat("Genes in T-cell object:", nrow(Tcells), "\n")
# cat("Variable genes:", length(VariableFeatures(Tcells)), "\n")
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(ggplot2)
# 
# summary_df <- data.frame(
#   Category = c("Cells after QC",
#                "Genes after QC",
#                "T cells",
#                "Variable genes"),
#   Count = c(24750, 16919, 6584, 2000)
# )
# 
# ggplot(summary_df,
#        aes(x = reorder(Category, Count),
#            y = Count,
#            fill = Category)) +
#   geom_bar(stat = "identity",
#            width = 0.7,
#            color = "black") +
#   geom_text(aes(label = Count),
#             vjust = -0.5,
#             size = 5) +
#   theme_classic(base_size = 14) +
#   labs(
#     title = "GSE111014 Dataset Summary",
#     x = "",
#     y = "Count"
#   ) +
#   theme(
#     plot.title = element_text(hjust = 0.5, face = "bold"),
#     legend.position = "none",
#     axis.text.x = element_text(angle = 20, hjust = 1)
#   ) +
#   scale_fill_brewer(palette = "Set2")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(ggplot2)
# 
# pie_df <- data.frame(
#   Group = c("T cells", "Other cells"),
#   Count = c(6584, 24750 - 6584)
# )
# 
# ggplot(pie_df,
#        aes(x = "", y = Count, fill = Group)) +
#   geom_bar(stat = "identity", width = 1) +
#   coord_polar("y", start = 0) +
#   theme_void() +
#   scale_fill_brewer(palette = "Pastel1") +
#   ggtitle("T-cell Fraction After QC")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# saveRDS(Tcells, "Tcell_final.rds")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Install remotes if you haven't already
# if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")
# 
# # Install sceasy from GitHub
# remotes::install_github("cellgeni/sceasy")
# 
# # Ensure the R anndata interface is installed
# install.packages("anndata")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Load the file
# load("/content/GSE111014_seurat_afterAnno.RData")
# 
# # Print all objects currently in the R environment
# ls()

!pip install starcatpy
!pip install scanpy anndata pandas numpy matplotlib

import scanpy as sc
import pandas as pd
import numpy as np

# Updated filename to match the existing converted file
adata = sc.read_h5ad("/content/GSE111014_converted.h5ad")

print(adata)

print("OBS columns:")
print(adata.obs.columns.tolist())

adata.obs.head()

print("Cells:", adata.n_obs)
print("Genes:", adata.n_vars)

for col in adata.obs.columns:
    print("\nCOLUMN:", col)
    print(adata.obs[col].astype(str).value_counts().head(20))

tcells = adata[
    adata.obs["celltype"].astype(str).str.contains(
        "T",
        case=False,
        na=False
    )
].copy()

print("T-cell count:", tcells.n_obs)
print("Gene count:", tcells.n_vars)

tcells.write(
    "/content/Tcells_only.h5ad"
)

"""The previous cell `8Y6B2VK52MJZ` should have saved the `tcells` object to a file named `/content/Tcells_only.h5ad`. If you are encountering a `FileNotFoundError`, it means this file was not created or has been deleted. Let's explicitly save it again to ensure it exists for the next steps."""

import scanpy as sc

# Load the full AnnData object
adata = sc.read_h5ad("/content/GSE111014_converted.h5ad")

# Extract T-cells based on the 'celltype' observation
tcells = adata[
    adata.obs["celltype"].astype(str).str.contains(
        "T",
        case=False,
        na=False
    )
].copy()

# Ensure the tcells object is saved to the correct path
tcells.write(
    "/content/Tcells_only.h5ad"
)

import scanpy as sc

# Load the tcells AnnData object from the H5AD file
tcells_loaded = sc.read_h5ad("/content/Tcells_only.h5ad")

# Display the loaded object to confirm
print(tcells_loaded)

# ============================================================
# 1. Imports
# ============================================================

import scanpy as sc
import pandas as pd
import numpy as np
import os

# ============================================================
# 2. Load T-cell object
# ============================================================

tcells = sc.read_h5ad("/content/Tcells_only.h5ad")

tcells

# ============================================================
# 3. Run StarCAT
# ============================================================

output_dir = "/content/starcat_results/Tcells"
os.makedirs(output_dir, exist_ok=True)

!starcat \
    --reference TCAT.V1 \
    --counts /content/Tcells_only.h5ad \
    --output-dir {output_dir} \
    --name TCELLS

# ============================================================
# 4. Read StarCAT output
# ============================================================

scores = pd.read_csv(
    f"{output_dir}/TCELLS.scores.txt",
    sep="\t",
    index_col=0
)

scores.head()

# ============================================================
# 5. Verify cell ordering
# ============================================================

print(scores.shape)
print(tcells.n_obs)

if not np.array_equal(
    scores.index.astype(str),
    tcells.obs_names.astype(str)
):
    scores = scores.loc[tcells.obs_names]

# ============================================================
# 6. Store all StarCAT program scores
# ============================================================

for col in scores.columns:
    if col != "Multinomial_Label":
        tcells.obs[col] = scores[col]

# ============================================================
# 7. Assign dominant program
# ============================================================

tcells.obs["Dominant_Program"] = (
    scores["Multinomial_Label"]
    .astype(str)
)

# ============================================================
# 8. Visualize all StarCAT programs
# ============================================================

sc.pl.umap(
    tcells,
    color="Dominant_Program",
    legend_loc="right margin",
    frameon=False,
    title="StarCAT Dominant Programs"
)

# ============================================================
# 9. Program frequencies
# ============================================================

prog_counts = (
    tcells.obs["Dominant_Program"]
    .value_counts()
)

prog_percent = (
    prog_counts /
    prog_counts.sum()
    * 100
)

summary = pd.DataFrame({
    "Program": prog_percent.index,
    "Percent": prog_percent.values
})

summary["Cumulative"] = (
    summary["Percent"]
    .cumsum()
)

summary

# ============================================================
# 10. Keep programs covering first 90% of cells
# ============================================================

top90 = summary[
    summary["Cumulative"] <= 90
]

top90

keep_programs = top90["Program"].tolist()

print("Programs retained:")
print(keep_programs)

# ============================================================
# 11. Create binary annotations
# ============================================================

for prog in keep_programs:

    tcells.obs[f"{prog}_binary"] = (
        tcells.obs["Dominant_Program"] == prog
    ).astype(int)

# ============================================================
# 12. UMAPs of retained programs
# ============================================================

for prog in keep_programs:

    sc.pl.umap(
        tcells,
        color=f"{prog}_binary",
        title=prog,
        cmap="viridis"
    )

# ============================================================
# 13. Multi-panel UMAP of retained programs
# ============================================================

binary_cols = [
    f"{prog}_binary"
    for prog in keep_programs
]

sc.pl.umap(
    tcells,
    color=binary_cols,
    ncols=4,
    cmap="viridis"
)

# ============================================================
# 14. Visualize T-cell states
# ============================================================
# Replace "cell_state" with your annotation column name
# Examples:
# cell_state
# celltype
# Tcell_State
# azimuth_celltype
# predicted.celltype.l2

print(tcells.obs.columns)

sc.pl.umap(
    tcells,
    color="cell_state",
    legend_loc="right margin",
    frameon=False,
    title="T-cell States"
)

# ============================================================
# 15. Compare T-cell states vs StarCAT programs
# ============================================================

state_program_table = pd.crosstab(
    tcells.obs["cell_state"],
    tcells.obs["Dominant_Program"]
)

state_program_table

# ============================================================
# 16. State-program percentages
# ============================================================

state_program_percent = (
    pd.crosstab(
        tcells.obs["cell_state"],
        tcells.obs["Dominant_Program"],
        normalize="index"
    ) * 100
)

state_program_percent.round(2)

# ============================================================
# 17. Heatmap
# ============================================================

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(14,8))

sns.heatmap(
    state_program_percent,
    cmap="viridis"
)

plt.title("T-cell States vs StarCAT Programs")
plt.xlabel("StarCAT Program")
plt.ylabel("T-cell State")

plt.show()

# ============================================================
# 18. Save final object
# ============================================================

tcells.write_h5ad(
    "/content/Tcells_starcat_annotated.h5ad"
)

print(tcells.obsm.keys())

sc.pl.umap(
    tcells,
    color=list(tcells.obs.columns[:3])
)

import os

output_dir = "/content/starcat_results/CLR_Tcells"
os.makedirs(output_dir, exist_ok=True)

!starcat \
--reference TCAT.V1 \
--counts /content/Tcells_only.h5ad \
--output-dir {output_dir} \
--name CLR_Tcells

scores = pd.read_csv(
    "/content/starcat_results/CLR_Tcells/CLR_Tcells.scores.txt",
    sep="\t",
    index_col=0
)

scores.head()

for c in scores.columns:
    tcells.obs[c] = scores[c]

if "Multinomial_Label" in scores.columns:
    # Align scores to tcell.obs_names before assignment to ensure correctness
    aligned_scores_for_tcell = scores.loc[tcell.obs_names, "Multinomial_Label"]
    tcell.obs["Dominant_Program"] = aligned_scores_for_tcell
else:
    print("Error: 'Multinomial_Label' column not found in the scores DataFrame.")

# The line below assigns to `tcells` (plural). If this is intended for a separate `tcells` object,
# ensure that `scores` is appropriate for it. For now, addressing the `tcell` (singular) issue.
# If `tcells` is meant to be the same as `tcell` at this point, this line is redundant and potentially confusing.
tcells.obs["Dominant_Program"] = scores["Multinomial_Label"]

prog_counts = (
    tcell.obs["Dominant_Program"]
    .value_counts()
)

prog_counts

prog_percent = (
    prog_counts /
    prog_counts.sum()
    * 100
)

prog_percent

summary = pd.DataFrame({
    "Program": prog_percent.index,
    "Percent": prog_percent.values
})

summary["Cumulative"] = (
    summary["Percent"]
    .cumsum()
)

top90 = summary[
    summary["Cumulative"] <= 90
]

top90

sc.pl.umap(
    tcells,
    color="Dominant_Program",
    legend_loc="right margin",
    frameon=False
)

states = [
    "CD4_EM",
    "CD4_CM",
    "CD8_CM",
    "CD4_Naive",
    "CD8_Naive",
    "CD8_EM",
    "gdT"
]

for state in states:

    tcells.obs[state+"_binary"] = (
        tcells.obs["Dominant_Program"] == state
    ).astype(int)

    sc.pl.umap(
        tcells,
        color=state+"_binary",
        title=state
    )

extra_states = ["CD8_TEMRA", "MAIT", "Treg"]

for state in extra_states:
    tcells.obs[f"{state}_binary"] = (
        tcells.obs["Dominant_Program"] == state
    ).astype(int)

    sc.pl.umap(
        tcells,
        color=f"{state}_binary",
        title=state,
        cmap="viridis"
    )

import matplotlib.pyplot as plt

state_counts = (
    tcells.obs["Dominant_Program"]
    .value_counts(normalize=True)
    *100
)

plt.figure(figsize=(8,5))

state_counts.plot.bar()

plt.ylabel("% T cells")
plt.xlabel("starCAT state")
plt.title("starCAT T-cell state composition")

plt.show()

print(scores.columns.tolist())

scores.head()

program_means = scores[['ASA', 'Proliferation']].mean(axis=0)

program_means = program_means.sort_values(
    ascending=False
)

program_means.head(20)

program_percent = (
    program_means /
    program_means.sum()
) * 100

program_percent

program_summary = pd.DataFrame({
    "Program": program_percent.index,
    "Percent": program_percent.values
})

program_summary["Cumulative"] = (
    program_summary["Percent"]
    .cumsum()
)

program_summary.head(30)

n90 = (
    program_summary["Cumulative"] >= 90
).idxmax() + 1

print(
    "Programs required for 90% coverage:",
    n90
)

top90_programs = (
    program_summary.iloc[:n90]
)

top90_programs

top90_programs.to_csv(
    "STARCAT_90percent_programs.csv",
    index=False
)

selected_programs = (
    top90_programs["Program"]
    .tolist()
)

sc.pl.umap(
    tcells,
    color=selected_programs,
    ncols=3
)

top10_programs = (
    program_means
    .sort_values(ascending=False)
    .head(10)
)

top10_programs

sc.pl.umap(
    tcells,
    color=top10_programs.index.tolist(),
    ncols=2
)

top20_programs = (
    program_means
    .sort_values(ascending=False)
    .head(20)
)

top20_programs

sc.pl.umap(
    tcells,
    color=top20_programs.index.tolist(),
    ncols=4
)

sc.pl.umap(
    tcells,
    color="Dominant_Program"
)

state_programs = tcells.obs.groupby(
    "Dominant_Program"
)[["ASA","Proliferation"]].mean()

state_programs

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(
    state_programs,
    cmap="viridis"
)

plt.show()

state_programs = tcells.obs.groupby(
    "Dominant_Program"
)[["ASA","Proliferation"]].mean()

print(scores.shape)

print(scores.columns.tolist())

import importlib.metadata

print(importlib.metadata.version('starcatpy'))

!pip show starcatpy

import os

for root, dirs, files in os.walk("/content/starcat_results"):
    for f in files:
        print(os.path.join(root, f))

import pandas as pd

scores = pd.read_csv(
    "/content/starcat_results/CLR_Tcells/CLR_Tcells.scores.txt",
    sep="\t",
    index_col=0
)

print(scores.shape)
print(scores.columns.tolist())
scores.head()

scores = pd.read_csv(
    "/content/starcat_results/CLR_Tcells/CLR_Tcells.scores.txt",
    sep="\t"
)

print(scores.columns)

import pandas as pd

usage = pd.read_csv(
    "/content/starcat_results/CLR_Tcells/CLR_Tcells.rf_usage_normalized.txt",
    sep="\t",
    index_col=0
)

print(usage.shape)
print(usage.columns[:20])

program_mean = usage.mean(axis=0)

program_mean = (
    program_mean
    .sort_values(ascending=False)
)

program_mean.head(20)

program_percent = (
    program_mean /
    program_mean.sum()
) * 100

summary = pd.DataFrame({
    "Program": program_percent.index,
    "Percent": program_percent.values
})

summary["Cumulative"] = (
    summary["Percent"]
    .cumsum()
)

summary.head(30)

top90 = summary[
    summary["Cumulative"] <= 90
]

top90

top10 = (
    program_mean
    .head(10)
    .index
    .tolist()
)

top10

for prog in top10:
    tcells.obs[prog] = usage[prog]

sc.pl.umap(
    tcells,
    color=top10,
    ncols=2
)

top20 = (
    program_mean
    .head(20)
    .index
    .tolist()
)

for prog in top20:
    tcells.obs[prog] = usage[prog]

sc.pl.umap(
    tcells,
    color=top20,
    ncols=4
)

top20 = (
    program_mean
    .head(20)
    .index
)

state_programs = (
    pd.concat(
        [tcells.obs["Dominant_Program"],
         usage[top20]],
        axis=1
    )
    .groupby("Dominant_Program")
    .mean()
)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,7))

sns.heatmap(
    state_programs,
    cmap="viridis"
)

plt.show()

state_programs.idxmax(axis=1)

selected = [
    "Cytotoxic",
    "TEMRA",
    "MAIT",
    "gdT",
    "Th22",
    "Multi-Cytokine",
    "ISG",
    "HLA",
    "CellCycle-S",
    "CellCycle-G2M"
]

for p in selected:
    tcells.obs[p] = usage[p]

sc.pl.umap(
    tcells,
    color=selected,
    ncols=2
)

state_to_program = {
    "CD4_CM":"Translation",
    "CD4_EM":"Translation",
    "CD4_Naive":"Translation",
    "CD8_CM":"Translation",
    "CD8_EM":"Cytotoxic",
    "CD8_Naive":"Translation",
    "CD8_TEMRA":"Cytotoxic",
    "MAIT":"Translation",
    "Treg":"Translation",
    "gdT":"Cytotoxic"
}

tcells.obs["Dominant_TCAT_Program"] = (
    tcells.obs["Dominant_Program"]
    .map(state_to_program)
)

sc.pl.umap(
    tcells,
    color="Dominant_TCAT_Program"
)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

sns.heatmap(
    state_programs,
    cmap="viridis"
)

plt.show()

[
"Cytotoxic",
"CellCycle-S",
"CellCycle-G2M",
"ISG",
"HLA",
"TEMRA",
"gdT",
"MAIT",
"Multi-Cytokine"
]

import matplotlib.pyplot as plt

labels = [
    "CD4_EM",
    "CD4_CM",
    "CD8_CM",
    "CD4_Naive",
    "CD8_Naive",
    "CD8_EM",
    "gdT"
]

sizes = [
    25.1,
    18.4,
    16.3,
    12.9,
    9.0,
    6.4,
    5.0
]

fig, ax = plt.subplots(figsize=(8,8))

wedges, texts, autotexts = ax.pie(
    sizes,
    labels=labels,
    autopct='%1.1f%%',
    startangle=90,
    pctdistance=0.8,
    textprops={'fontsize':12}
)

# donut appearance
centre_circle = plt.Circle((0,0),0.55,fc='white')
fig.gca().add_artist(centre_circle)

ax.set_title(
    "Major T-cell States (>93% of T cells)",
    fontsize=16,
    pad=20
)

plt.tight_layout()

plt.savefig(
    "starCAT_Tcell_states_piechart.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

states = [
    'CD4_EM', 'CD4_CM', 'CD8_CM', 'CD4_Naive',
    'CD8_Naive', 'CD8_TEMRA', 'MAIT', 'Treg',
    'gdT', 'NKT'
]

values = np.array([26, 22, 22, 20, 18, 17, 18, 19, 18, 20])

# Convert to percentages
percentages = values / values.sum() * 100

plt.figure(figsize=(8,8))
plt.pie(
    percentages,
    labels=states,
    autopct='%1.1f%%',
    startangle=90
)

centre_circle = plt.Circle((0,0), 0.55, fc='white')
plt.gca().add_artist(centre_circle)

plt.title('StarCAT T-cell State Composition')
plt.tight_layout()
plt.show()

!pip install scanpy anndata pandas numpy seaborn matplotlib scikit-learn

import scanpy as sc
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

adata = sc.read_h5ad("/content/GSE111014_converted (1).h5ad")
print(adata)

sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

sc.pp.highly_variable_genes(adata, n_top_genes=2000)
adata = adata[:, adata.var.highly_variable]

sc.pp.scale(adata, max_value=10)

print(adata.obs.columns)

tcell = adata[adata.obs["celltype"].str.contains("T", case=False)].copy()
print(tcell)

state_markers = {
    "naive": ["CCR7", "TCF7", "IL7R"],
    "cytotoxic": ["GZMB", "PRF1", "NKG7"],
    "exhausted": ["PDCD1", "CTLA4", "LAG3", "TIGIT"],
    "memory": ["IL7R", "LTB", "GPR183"],
    "cycling": ["MKI67", "TOP2A"]
}

for state, genes in state_markers.items():
    sc.tl.score_genes(tcell, gene_list=genes, score_name=state)

programs = {
    "exhaustion_program": ["PDCD1", "LAG3", "TIGIT", "HAVCR2"],
    "cytotoxic_program": ["GZMB", "PRF1", "NKG7"],
    "naive_program": ["CCR7", "LEF1", "TCF7"],
    "activation_program": ["IFNG", "TNF", "CD69", "IL2RA"],
    "proliferation_program": ["MKI67", "TOP2A", "STMN1"]
}

for p, genes in programs.items():
    sc.tl.score_genes(tcell, gene_list=genes, score_name=p)

for p in programs.keys():
    tcell.obs[p + "_z"] = (
        tcell.obs[p] - tcell.obs[p].mean()
    ) / tcell.obs[p].std()

state_map = {
    "Naive-like": ["naive_program_z"],
    "Cytotoxic": ["cytotoxic_program_z"],
    "Exhausted": ["exhaustion_program_z"],
    "Activated": ["activation_program_z"],
    "Proliferating": ["proliferation_program_z"]
}

state_scores = pd.DataFrame(index=tcell.obs_names)

for state, cols in state_map.items():
    state_scores[state] = tcell.obs[cols].mean(axis=1)

tcell.obs["TSTScope_state"] = state_scores.idxmax(axis=1)
tcell.obs["TSTScope_score"] = state_scores.max(axis=1)

!pip install leidenalg
sc.pp.pca(tcell)
sc.pp.neighbors(tcell)
sc.tl.umap(tcell)
sc.tl.leiden(tcell)

sc.pl.umap(tcell, color=["naive", "cytotoxic", "exhausted", "memory", "cycling"])

sc.pl.umap(tcell, color=["TSTScope_state", "TSTScope_score"])

sc.pl.umap(
    tcell,
    color=[
        "naive_program",
        "cytotoxic_program",
        "exhaustion_program",
        "activation_program",
        "proliferation_program"
    ]
)

comparison = pd.crosstab(
    tcell.obs["TSTScope_state"],
    tcell.obs["leiden"],
    normalize="index"
)

print(comparison)

comparison = pd.crosstab(
    tcell.obs["TSTScope_state"],
    tcell.obs["leiden"],
    normalize="index"
)

print(comparison)

plt.figure(figsize=(10,6))

sns.heatmap(
    comparison,
    annot=True,
    cmap="YlGnBu",
    fmt=".2f"
)

plt.title("TSTScope States vs Leiden Clusters")
plt.xlabel("Leiden Cluster")
plt.ylabel("TSTScope State")
plt.tight_layout()
plt.show()

cluster_comp = pd.crosstab(
    tcell.obs["leiden"],
    tcell.obs["TSTScope_state"],
    normalize="index"
)

cluster_comp.plot(
    kind="bar",
    stacked=True,
    figsize=(10,6)
)

plt.ylabel("Fraction of Cells")
plt.xlabel("Leiden Cluster")
plt.title("TSTScope State Composition per Leiden Cluster")
plt.legend(
    title="TSTScope State",
    bbox_to_anchor=(1.05,1),
    loc="upper left"
)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))

sns.countplot(
    data=tcell.obs,
    x="TSTScope_state",
    order=tcell.obs["TSTScope_state"].value_counts().index
)

plt.xticks(rotation=45)
plt.title("TSTScope State Abundance")
plt.xlabel("")
plt.ylabel("Number of Cells")
plt.tight_layout()
plt.show()

sc.pl.umap(
    tcell,
    color="leiden",
    legend_loc="on data",
    frameon=False,
    title="Leiden Clusters"
)

sc.pl.umap(
    tcell,
    color="TSTScope_state",
    frameon=False,
    title="TSTScope Predicted T-cell States"
)

sc.pl.umap(
    tcell,
    color="leiden",
    legend_loc="on data",
    size=40,
    title="Leiden Clusters on UMAP"
)

sc.pl.umap(
    tcell,
    color=[
        "naive_program",
        "cytotoxic_program",
        "exhaustion_program",
        "activation_program",
        "proliferation_program"
    ],
    cmap="viridis",
    ncols=3
)

df = tcell.obs[
    ["leiden",
     "naive", "cytotoxic", "exhausted",
     "exhaustion_program", "cytotoxic_program"]
]

df_melt = df.melt(id_vars="leiden", var_name="signature", value_name="score")

plt.figure(figsize=(12,5))
sns.boxplot(data=df_melt, x="signature", y="score")
plt.xticks(rotation=45)
plt.show()

summary = tcell.obs.groupby("TSTScope_state")[[
    "exhaustion_program",
    "cytotoxic_program",
    "activation_program"
]].mean()

summary.plot(kind="bar", figsize=(8,5))
plt.title("TSTScope-like Program Activity by Predicted State")
plt.ylabel("Mean score")
plt.show()

starcat_scores = tcell.obs[
    ["naive", "cytotoxic", "exhausted", "memory", "cycling"]
]

tcell.obs["STARCAT_state"] = starcat_scores.idxmax(axis=1)

tcell.obs["STARCAT_state"].value_counts()

program_cols = [
    "naive_program",
    "cytotoxic_program",
    "exhaustion_program",
    "activation_program",
    "proliferation_program"
]

heatmap_data = (
    tcell.obs
    .groupby("TSTScope_state")[program_cols]
    .mean()
)

plt.figure(figsize=(8,5))

sns.heatmap(
    heatmap_data,
    annot=True,
    cmap="RdYlBu_r"
)

plt.title("TSTScope Programs Across States")
plt.tight_layout()
plt.show()

program_cols = [
    "naive_program",
    "cytotoxic_program",
    "exhaustion_program",
    "activation_program",
    "proliferation_program"
]

heatmap_data = (
    tcell.obs
    .groupby("TSTScope_state")[program_cols]
    .mean()
)

plt.figure(figsize=(10,6))

ax = sns.heatmap(
    heatmap_data,
    annot=True,
    cmap="RdYlBu_r",
    fmt=".2f",
    linewidths=0.5
)

# Fix labels
ax.set_yticklabels(
    ax.get_yticklabels(),
    rotation=0,
    fontsize=12
)

ax.set_xticklabels(
    ax.get_xticklabels(),
    rotation=45,
    ha="right",
    fontsize=11
)

plt.ylabel("TSTScope State", fontsize=12)
plt.xlabel("Programs", fontsize=12)
plt.title("TSTScope Programs Across States", fontsize=14)

plt.tight_layout()
plt.show()

comparison = pd.crosstab(
    tcell.obs["STARCAT_state"],
    tcell.obs["TSTScope_state"],
    normalize="index"
)

plt.figure(figsize=(8,6))

sns.heatmap(
    comparison,
    annot=True,
    cmap="Blues",
    fmt=".2f"
)

plt.title("STARCAT State vs TSTScope State")
plt.xlabel("TSTScope State")
plt.ylabel("STARCAT State")
plt.tight_layout()
plt.show()