# -*- coding: utf-8 -*-
"""Skin Cancer Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bryYDm7nqe-s1Vlm8ish0Mj1hyA6Xume
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

df = pd.read_csv("HAM10000_metadata.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

df.info()
df.describe(include="all")
print(df.columns.tolist())

df.isnull().sum()

missing = df.isnull().sum()

missing_percentage = (missing / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percentage
})

missing_table

print(df["dx"].value_counts())

plt.figure(figsize=(10, 5))

sns.countplot(
    data=df,
    x="dx",
    order=df["dx"].value_counts().index
)

plt.title("Distribution of Skin Lesion Diagnoses")
plt.xlabel("Diagnosis")
plt.ylabel("Number of Images")
plt.xticks(rotation=45)
plt.show()

print(df["sex"].value_counts(dropna=False))
print(df["localization"].value_counts(dropna=False))
print(df["dx_type"].value_counts(dropna=False))
print(df["age"].describe())

plt.figure(figsize=(8, 5))

plt.hist(df["age"].dropna(), bins=30)

plt.xlabel("Age")
plt.ylabel("Number of Patients/Images")
plt.title("Age Distribution")

plt.show()

print("Total rows:", len(df))
print("Unique lesions:", df["lesion_id"].nunique())
print("Unique images:", df["image_id"].nunique())

duplicate_lesions = df["lesion_id"].value_counts()

duplicate_lesions[duplicate_lesions > 1].head(20)

from google.colab import drive
drive.mount('/content/drive')

import os

print(os.listdir('/content/drive/MyDrive'))

image_folder = "/content/drive/MyDrive/HAM10000_images_part_1"



import os

print("Number of files:", len(os.listdir(image_folder)))
print("First 10 files:")
print(os.listdir(image_folder)[:10])

metadata_path = "/content/HAM10000_metadata.csv"

import pandas as pd

metadata = pd.read_csv(metadata_path)

print(metadata.head())
print(metadata.shape)
print(metadata.columns)

print(metadata['dx'].value_counts())

metadata['image_path'] = metadata['image_id'].apply(
    lambda x: os.path.join(image_folder, x + '.jpg')
)

metadata = metadata[metadata['image_path'].apply(os.path.exists)]

print("Images successfully matched:", len(metadata))

# Check the class distribution of our 5,000 images
print("Total matched images:", len(metadata))
print("\nClass distribution:")
print(metadata['dx'].value_counts())

print("\nClass percentages:")
print((metadata['dx'].value_counts(normalize=True) * 100).round(2))

# Check for missing values
print("Missing values:")
print(metadata.isnull().sum())

# Check for duplicate images
print("\nDuplicate image IDs:", metadata['image_id'].duplicated().sum())

from sklearn.model_selection import train_test_split

# First split: 80% training, 20% temporary
train_df, temp_df = train_test_split(
    metadata,
    test_size=0.20,
    stratify=metadata['dx'],
    random_state=42
)

# Second split: divide the 20% temporary set equally
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df['dx'],
    random_state=42
)

print("Training images:", len(train_df))
print("Validation images:", len(val_df))
print("Test images:", len(test_df))

print("TRAIN:")
print(train_df['dx'].value_counts())

print("\nVALIDATION:")
print(val_df['dx'].value_counts())

print("\nTEST:")
print(test_df['dx'].value_counts())

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

# Training augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    vertical_flip=True,
    fill_mode='nearest'
)

# Validation/test: only normalization
val_test_datagen = ImageDataGenerator(
    rescale=1./255
)

train_generator = train_datagen.flow_from_dataframe(
    dataframe=train_df,
    x_col='image_path',
    y_col='dx',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True,
    seed=42
)

val_generator = val_test_datagen.flow_from_dataframe(
    dataframe=val_df,
    x_col='image_path',
    y_col='dx',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

test_generator = val_test_datagen.flow_from_dataframe(
    dataframe=test_df,
    x_col='image_path',
    y_col='dx',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

print("Class mapping:")
print(train_generator.class_indices)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Get class names in the same order used by the generator
class_names = list(train_generator.class_indices.keys())

# Convert labels to integer indices
y_train = train_df['dx'].map(train_generator.class_indices).values

# Calculate balanced class weights
weights = compute_class_weight(
    class_weight='balanced',
    classes=np.arange(len(class_names)),
    y=y_train
)

class_weights = dict(enumerate(weights))

print("Class names:")
print(class_names)

print("\nClass weights:")
for i, weight in class_weights.items():
    print(f"{class_names[i]}: {weight:.3f}")

images, labels = next(train_generator)

print("Image batch shape:", images.shape)
print("Label batch shape:", labels.shape)
print("Pixel range:", images.min(), "to", images.max())

import tensorflow as tf
from tensorflow.keras import layers, models

num_classes = 7

model = models.Sequential([
    # Input
    layers.Input(shape=(224, 224, 3)),

    # Block 1
    layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25),

    # Block 2
    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25),

    # Block 3
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.30),

    # Classification head
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.50),

    layers.Dense(num_classes, activation='softmax')
])

model.summary()

from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("Model compiled successfully!")

import numpy as np
from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_generator.classes),
    y=train_generator.classes
)

class_weights = dict(enumerate(class_weights))

print("Class Weights:")
for class_id, weight in class_weights.items():
    print(f"Class {class_id}: {weight:.4f}")

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

callbacks = [

    EarlyStopping(
        monitor='val_loss',
        patience=7,
        restore_best_weights=True,
        verbose=1
    ),

    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.3,
        patience=3,
        min_lr=1e-7,
        verbose=1
    ),

    ModelCheckpoint(
        'best_skin_disease_cnn.keras',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    )
]

print("Callbacks ready!")

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=40,
    class_weight=class_weights,
    callbacks=callbacks
)